#!/usr/bin/python2.6
import curses
import time
import optparse
import readers
import sys
import templates
from string import Template

def screen_print(scr, output):
    scr.refresh()
    scr.addstr(0, 0, output)

#curses.wrapper(main)

def call_back_test(option, opt_str, value, parser):
    print("option: ")
    print(option)
    print("opt_str: ")
    print(opt_str)
    print("value: ")
    print(value)
    print("parser: ")
    print(parser.values)

def get_link_data(interfaces, names)
    if value == 'all':
        data = readers.ip_s_link(interfaces.keys())
    else:
        try: interfaces[value]
        except KeyError:
            print("%s is not a valid interface" % value)
            parser.print_help()
            sys.exit(1)
        data = readers.ip_s_link(value)
    return data

    
def link(stdscr, option, opt_str, value, parser):
    interfaces = readers.ip_a()
    original_data = get_link_data(interfaces, value)
    output = ''
    for name in data.keys():
        ips = ', '.join(interfaces[name]['ipv4'])
        section = Template(templates.link).safe_substitute(data[name], ips=ips, name=name)
        output += section + "\n\n"
    stdscr.addstr(0, 0, output)
    stdscr.refresh()
    time.sleep(5)
    #screen_print(stdscr, output)


def link_wrapper(option, opt_str, value, parser):
   curses.wrapper(link, option, opt_str, value, parser) 

# Parse settings from commandline options
# TODO: add program description including that must be run as root
cli_parser = optparse.OptionParser(usage='%prog [OPTIONS]')
cli_parser.add_option('-d', '--d', dest='delay', default=5, type='int', metavar='SECONDS', \
                      help="delay between updates [default: %default seconds]")
cli_parser.add_option('-l', '--link', dest='link', type='string', metavar='INTERFACE', action='callback', callback=link_wrapper, \
                      help="PUT STUFF HERE [default: %default]")

(opts, args) = cli_parser.parse_args()
